function K1 = K1_basic(in)
% *** interesting that things can fail silently if a struct
    K1 = transonicMerge(@(in) 1, ... 
        @(in) in.geometry.wing.AR.v * (in.condition.M.^2 - 1) ./ (4*in.geometry.wing.AR.v * sqrt(in.condition.M.^2 - 1) -2) * cosd(in.geometry.wing.le_sweep.v) , ...
            in );
end
