function K1 = K1_basic(in)
    K1 = transonicMerge(@(in) 1, ... 
        @(in) in.geometry.wing.AR * (in.condition.M.^2 - 1) ./ (4*in.geometry.wing.AR*sqrt(in.condition.M.^2 - 1) -2) * cosd(in.geometry.wing.le_sweep) , ...
            in );
end
